// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OpenCoreGen from "./OpenCore.gen";

function useAuthState(prim) {
  return OpenCoreGen.useAuthState(prim);
}

export {
  useAuthState ,
}
/* ./OpenCore.gen Not a pure module */
