// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function toOption(n) {
  if (n >= 0) {
    return n;
  }
  
}

function match(t, found, invalid) {
  if (t >= 0) {
    return Curry._1(found, t);
  } else {
    return Curry._1(invalid, undefined);
  }
}

export {
  toOption ,
  match ,
}
/* No side effect */
