// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UseFullPathGen from "./UseFullPath.gen";

function useAuthState(prim) {
  return UseFullPathGen.useAuthState(prim);
}

export {
  useAuthState ,
}
/* ./UseFullPath.gen Not a pure module */
