// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UseRootModuleGen from "./UseRootModule.gen";

function useAuthState(prim) {
  return UseRootModuleGen.useAuthState(prim);
}

export {
  useAuthState ,
}
/* ./UseRootModule.gen Not a pure module */
